### ISSUE TITLE
gmusicapi.exceptions.NotLoggedIn

### ISSUE THREAD

**Issue by paullew** [Athou/google-music-downloader#2]
Hi, 

How do I log in to google to run this?

Here's the output of my first run:

```
$ python gmusic-dl.py <email> <albumid>
Password:
Traceback (most recent call last):
  File "gmusic-dl.py", line 34, in <module>
    album = api.get_album_info(albumId)
  File "<decorator-gen-138>", line 2, in get_album_info
  File "/usr/local/lib/python2.7/site-packages/gmusicapi/utils/utils.py", line 293, in wrapper
    return function(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 2029, in get_album_info
    return self._make_call(mobileclient.GetAlbum, album_id, include_tracks)
  File "/usr/local/lib/python2.7/site-packages/gmusicapi/clients/shared.py", line 84, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 209, in perform
    response = session.send(req_kwargs, cls.required_auth)
  File "/usr/local/lib/python2.7/site-packages/gmusicapi/session.py", line 84, in send
    raise NotLoggedIn
gmusicapi.exceptions.NotLoggedIn
```

**Comment by paullew** [comment]
Sorry, it made sense once I read the code. 

I didn't realise the password prompt is actually asking for my google password! It looks like a normal sudo password prompt, so I gave it my unix password out of habit.  

It works fine once I type in my google password. I'll close this issue.
